### ISSUE TITLE
undefined error

### ISSUE THREAD

**Issue by yamkim** [innovationacademy-kr/slabs-slackbot#2]
partA혹은 partB에 기재되어 있지 않는 slack command를 받을 때 undefined 처리

**Comment by kenu** [comment]
![스크린샷 2021-05-18 오후 3 03 02](https://user-images.githubusercontent.com/718691/118599290-456e0300-b7ea-11eb-8d6f-97403540cfc1.png)

유사한 경우 같은데, 메시지 수정될 필요가 있어 보입니다.
너무 개발틱해요.

**Comment by weg901127** [comment]
맞습니다 그리고 app이 요청이 늦어지면 어떤오류라도 상관없이 timout이더라구요... 그래서 일단 status를 200으로 통일하고 그다음에 해당하는 에러메세지를 전송해야할듯합니다... ㅠㅠ

**Comment by kenu** [comment]
"👻귀신이 응답을 붙잡고 있어요. ㅠㅠ 나중에 다시 시도해 주세요~" 이런 거 어때요. :)
"서버가 파업중입니다."

**Comment by weg901127** [comment]
좋습니다 ㅎㅎ 좀 소프트하게 바꾸겠습니다 ㅎㅎ
